# @package _global_


domain_rand:
  default_dof_pos_bias:
    mode: startup
    params:
      joint_names: [".*"]
      pos_distribution_params: [-0.01, 0.01]
      operation: add
      distribution: uniform

  rigid_body_com:
    mode: startup
    params:
      body_names: torso_link
      com_range:
        x: [-0.025, 0.025]
        y: [-0.05, 0.05]
        z: [-0.05, 0.05]

  rigid_body_material:
    mode: startup
    params:
      body_names: ".*"
      static_friction_range: [0.3, 1.6]
      dynamic_friction_range: [0.3, 1.2]
      restitution_range: [0.0, 0.5]
      num_buckets: 64

  push_by_setting_velocity:
    mode: interval
    interval_range_s: [1.0, 3.0]
    params:
      velocity_range:
        x: [-0.5, 0.5]
        y: [-0.5, 0.5]
        z: [-0.2, 0.2]
        roll: [-0.52, 0.52]
        pitch: [-0.52, 0.52]
        yaw: [-0.78, 0.78]
